// @no-log
POST http://localhost:8080/transactions
Accept: application/xml
Content-Type: application/xml

<transaction>
    <reference>test</reference>
    <amount>10</amount>
</transaction>

###
// @no-log
POST http://localhost:8080/transactions?reference=anotherTest&amount=150
Accept: application/json

{ "reference": "anotherTest", "amount": 150.54 }

> {%
client.global.set( 'transaction-id', response.body[ 'id' ] );
 %}

###
// @no-log
GET http://localhost:8080/transactions
Accept: application/xml

###
// @no-log
GET http://localhost:8080/transactions/find?id={{transaction-id}}
Accept: application/json